platform:
  - x64

environment:
  nodejs_version: "7.9.0"
  access_token:
    secure: 4Nz2Y0bVRKdKUBmNVYN6XTLhf3tR1B3zKXN4yHKgR68EYc+3iY3nQuX5SJgJRr9p
  github_email:
    secure: YPjJuUxFqpDTxqi5tffpUiMz2Y62dgkDavR83tI59B4=

install:
  - ps: Install-Product node
  - set CI=true
  - appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run test:ci
  - npm run docs


deploy_script:
  - ps: .\deploy-script.ps1

build: off
